@startuml
hide circle
skinparam classAttributeIconSize 0

Class "{abstract}\nCommand" as Command {
  +execute(Model): CommandResult
}
Class RemarkCommand {
  -studentId: StudentId
  -remark: Remark
  +COMMAND_WORD: String
  +execute(Model): CommandResult
}
Class CommandException
Class StudentId
Class Remark {
  +value: String
}

RemarkCommand -up-|> Command
Command ..> CommandException: throws >
RemarkCommand .right.> CommandException: throws >
RemarkCommand --> StudentId
RemarkCommand --> Remark
@enduml
