@startuml
hide circle
skinparam classAttributeIconSize 0

Class "<<interface>>\nParser" as Parser
Class RemarkCommandParser {
  +parse(args): RemarkCommand
}
Class ParseException
Class RemarkCommand

RemarkCommandParser .up.|> Parser
Parser .right.> ParseException: throws >
RemarkCommandParser .right.> ParseException: throws >
RemarkCommandParser ..> RemarkCommand: creates >
@enduml
